# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c6eb02ab807d4b507c8b53d9d58ebec77376d9a273cf2fa97827239998fe544dc267113b78d28eca52f0d7efac9dcc81e998f6f5e404b4ad42a5c17d2e840a4

test:
  secret_key_base: 52f42041f2b488ee5bc8e3ab6390e071a1f01ebd603a0ccd30df574d0b8620830827a0e198c71463905a1e9ede1b31c886b664c4e321a7c4ca81fe66dae1d141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
